# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [micheal senerchia, Taryn price, laurence severtson, gregory lamar]
patreon: # Replace with a single Patreon username micheal senerchia
open_collective: # Replace with a single Open Collective username Gregory Lamar
ko_fi: # Replace with a single Ko-fi username Taryn price
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username Gregory Lamar
issuehunt: # Replace with a single IssueHunt username Gregory Lamar
otechie: # Replace with a single Otechie username Gregory Lamar
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['support@markbookapp.com', 'mrichardson@acadiemgroup.com']
