# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [kate susmouski, Fomina Ekaterina, laurence severtson]
patreon: # Replace with a single Patreon username Micheal Senerchia
open_collective: # Replace with a single Open Collective username Taryn Price
ko_fi: # Replace with a single Ko-fi username kate susmouski
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username Gregory Lamar
issuehunt: # Replace with a single IssueHunt username Fomina Ekaterina
otechie: # Replace with a single Otechie username laurence severtson
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['Email:fomina@dsol.ru', 'TG: @kate_4mina', '+7 (915) 742-47-71']
